NumPy Arrays


In [2]:
import numpy as np

In [3]:
#Creating arrays
import numpy as np
a=[10,20,30]
b=np.array(a)
print(b)

[10 20 30]


In [5]:
a=[[10,20],[40,50]]
b=np.array(a)
print(b)

[[10 20]
 [40 50]]


In [6]:
a[0][1]

20

In [7]:
a=[[[10,20],[30,40]],[[50,60],[80,90]]]
b=np.array(a)
print(b)

[[[10 20]
  [30 40]]

 [[50 60]
  [80 90]]]


In [8]:
a[1][0][1]

60

In [9]:
a=[10,20,30]
b=np.asarray(a,float)
print(b)

[10. 20. 30.]


In [10]:
a=[[10,20],[30,40]]
b=np.asarray(a,float,'c')
print(b)

[[10. 20.]
 [30. 40.]]


In [11]:
for rec in np.nditer(b):
    print(rec)

10.0
20.0
30.0
40.0
